---
- hosts: db 
  become: yes
  gather_facts: 0
  tasks:

     - name: Update the system
       yum:
         name: '*'
         state: latest
       tags:
        - update    
     - name: install httpd
       package: 
         name: httpd
         state: present
       tags:
         - install   
     - name: start the httpd Daemon
       systemd:
         name: httpd
         state: started
         enabled: yes
       tags:
         - deemon  
     - name: copy index file to target
       copy:
         src: index.html
         dest: /var/www/html/index,html
       tags:
         - file_copy

         










