---
- hosts: db 
  become: yes
  gather_facts: 0
  tasks:
     - name: install packages
       yum:
         name: "{{item}}"
         state: present
       loop:
         - curl
         - finger
         - wget
         - httpd
         - ntp
