---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
     user_name: loic2025
     group_name: devops
  vars_files:
     - variables.yml    
  tasks:
     - name: check the time
       command: dgfyfyfyyu
 #      when: ansible_distribution == "loic" or ansible_processor_nproc == 2
     - name: create user loic
       user:
          name: "{{user_name}}"
          comment: loic Admin
     - name: create group
       group:
          name: "{{group_name}}"
          state: present
     -  name: Install package
        package:
          name: "{{pkg_name}}"
          state: present